INSERT INTO estados (nombre, created_at, updated_at)
    VALUES
     ('Amazonas', CURDATE(), CURDATE()),
     ('Anzoátegui', CURDATE(), CURDATE()),
     ('Apure', CURDATE(), CURDATE()),
     ('Aragua', CURDATE(), CURDATE()),
     ('Barinas', CURDATE(), CURDATE()),
     ('Bolivar', CURDATE(), CURDATE()),
     ('Carabobo', CURDATE(), CURDATE()),
     ('Cojedes', CURDATE(), CURDATE()),
     ('Delta Amacuro', CURDATE(), CURDATE()),
     ('Distrito Capital', CURDATE(), CURDATE()),
     ('Falcón', CURDATE(), CURDATE()),
     ('Guárico', CURDATE(), CURDATE()),
     ('Lara', CURDATE(), CURDATE()),
     ('Mérida', CURDATE(), CURDATE()),
     ('Miranda', CURDATE(), CURDATE()),
     ('Monagas', CURDATE(), CURDATE()),
     ('Nueva Esparta', CURDATE(), CURDATE()),
     ('Portuguesa', CURDATE(), CURDATE()),
     ('Sucre', CURDATE(), CURDATE()),
     ('Táchira', CURDATE(), CURDATE()),
     ('Trujillo', CURDATE(), CURDATE()),
     ('Vargas', CURDATE(), CURDATE()),
     ('Yaracuy', CURDATE(), CURDATE()),
     ('Zulia', CURDATE(), CURDATE());
    