INSERT INTO municipios (nombre, estado_id, created_at, updated_at)
    VALUES
     ('Atures', 1, CURDATE(), CURDATE()),
     ('Alto Orinoco', 1, CURDATE(), CURDATE()),
     ('Atabapo', 1, CURDATE(), CURDATE()),
     ('Autana', 1, CURDATE(), CURDATE()),
     ('Manaoiare', 1, CURDATE(), CURDATE()),
     ('Maroa', 1, CURDATE(), CURDATE()),
     ('Río Negro', 1, CURDATE(), CURDATE()),

     ('Simón Bolivar', 2, CURDATE(), CURDATE()),
     ('Anaco', 2, CURDATE(), CURDATE()),
     ('Aragua', 2, CURDATE(), CURDATE()),
     ('Diego Bautista Urbaneja', 2, CURDATE(), CURDATE()),
     ('Fernando de Peñalver', 2, CURDATE(), CURDATE()),
     ('Francisco del Carmen Carvaja', 2, CURDATE(), CURDATE()),
     ('Francisco de Miranda', 2, CURDATE(), CURDATE()),
     ('Guanta', 2, CURDATE(), CURDATE()),
     ('Independencia', 2, CURDATE(), CURDATE()),
     ('José Gregorio Monagas', 2, CURDATE(), CURDATE()),
     ('Juan Antonio Sotillo', 2, CURDATE(), CURDATE()),
     ('Juan Manuel Cajigal', 2, CURDATE(), CURDATE()),
     ('Libertad', 2, CURDATE(), CURDATE()),
     ('Manuel Ezequiel Bruzual', 2, CURDATE(), CURDATE()),
     ('Pedro María Freites', 2, CURDATE(), CURDATE()),
     ('Píritu', 2, CURDATE(), CURDATE()),
     ('San José de Guanipa', 2, CURDATE(), CURDATE()),    
     ('San Juan de Capistrano', 2, CURDATE(), CURDATE()),
     ('Santa Ana', 2, CURDATE(), CURDATE()),
     ('Simón Rodríguez', 2, CURDATE(), CURDATE()),
     ('Sir Arthur Mc Gregor', 2, CURDATE(), CURDATE()),

     ('San Fernando', 3, CURDATE(), CURDATE()),
     ('Achaguas', 3, CURDATE(), CURDATE()),
     ('Biruaca', 3, CURDATE(), CURDATE()),
     ('Muñoz', 3, CURDATE(), CURDATE()),
     ('Páez', 3, CURDATE(), CURDATE()),
     ('Pedro Camejo', 3, CURDATE(), CURDATE()),
     ('Rómulo Gallegos', 3, CURDATE(), CURDATE()),

     ('Girardot', 4, CURDATE(), CURDATE()),
     ('Bolívar', 4, CURDATE(), CURDATE()),
     ('Camatagua', 4, CURDATE(), CURDATE()),
     ('Francisco Linares Alcántara', 4, CURDATE(), CURDATE()),
     ('José Ángel Lamas', 4, CURDATE(), CURDATE()),
     ('José Félix Ribas', 4, CURDATE(), CURDATE()),
     ('José Rafael Revenga', 4, CURDATE(), CURDATE()),
     ('Libertador', 4, CURDATE(), CURDATE()),
     ('Mario Briceño Iragorry', 4, CURDATE(), CURDATE()),
     ('Ocumare', 4, CURDATE(), CURDATE()),
     ('San Casimiro', 4, CURDATE(), CURDATE()),
     ('San Sebastián', 4, CURDATE(), CURDATE()),
     ('Santiago Mariño', 4, CURDATE(), CURDATE()),
     ('Santos Michelena', 4, CURDATE(), CURDATE()),
     ('Sucre', 4, CURDATE(), CURDATE()),
     ('Tovar', 4, CURDATE(), CURDATE()),
     ('Urdaneta', 4, CURDATE(), CURDATE()),
     ('Zamora', 4, CURDATE(), CURDATE()),

     ('Alberto Arévalo Torrealba', 5, CURDATE(), CURDATE()),
     ('Antonio José de Sucre', 5, CURDATE(), CURDATE()),
     ('Cruz Paredes', 5, CURDATE(), CURDATE()),
     ('Andrés Eloy Blanco', 5, CURDATE(), CURDATE()),
     ('Sosa', 5, CURDATE(), CURDATE()),
     ('Rojas', 5, CURDATE(), CURDATE()),
     ('Arismendi', 5, CURDATE(), CURDATE()),
     ('Barinas', 5, CURDATE(), CURDATE()),
     ('Bolívar', 5, CURDATE(), CURDATE()),
     ('Ezequiel ', 5, CURDATE(), CURDATE()),
     ('Zamora', 5, CURDATE(), CURDATE()),
     ('Obispos', 5, CURDATE(), CURDATE()),
     ('Pedraza', 5, CURDATE(), CURDATE()),

     ('Heres', 6, CURDATE(), CURDATE()),
     ('Angostura', 6, CURDATE(), CURDATE()),
     ('Caroní', 6, CURDATE(), CURDATE()),
     ('Cedeño', 6, CURDATE(), CURDATE()),
     ('El Callao', 6, CURDATE(), CURDATE()),
     ('Gran Sabana', 6, CURDATE(), CURDATE()),
     ('Padre Pedro Chien', 6, CURDATE(), CURDATE()),
     ('Piar', 6, CURDATE(), CURDATE()),
     ('Roscio', 6, CURDATE(), CURDATE()),
     ('Sifontes', 6, CURDATE(), CURDATE()),
     ('Sucre', 6, CURDATE(), CURDATE()),

     ('Valencia', 7, CURDATE(), CURDATE()),
     ('Bejuma', 7, CURDATE(), CURDATE()),
     ('Carlos Arvelo', 7, CURDATE(), CURDATE()),
     ('Diego Ibarra', 7, CURDATE(), CURDATE()),
     ('Guacara', 7, CURDATE(), CURDATE()),
     ('Juan José Mora', 7, CURDATE(), CURDATE()),
     ('Libertador', 7, CURDATE(), CURDATE()),
     ('Los Guayos', 7, CURDATE(), CURDATE()),
     ('Miranda', 7, CURDATE(), CURDATE()),
     ('Montalbán', 7, CURDATE(), CURDATE()),
     ('Naguanagua', 7, CURDATE(), CURDATE()),
     ('Puerto Cabello', 7, CURDATE(), CURDATE()),
     ('San Diego', 7, CURDATE(), CURDATE()),
     ('San Joaquín', 7, CURDATE(), CURDATE()),

     ('Ezequiel Zamora', 8, CURDATE(), CURDATE()),
     ('Anzoátegui', 8, CURDATE(), CURDATE()),
     ('Girardot', 8, CURDATE(), CURDATE()),
     ('Lima Blanco', 8, CURDATE(), CURDATE()),
     ('Pao de San Juan Bautista', 8, CURDATE(), CURDATE()),
     ('Ricaurte', 8, CURDATE(), CURDATE()),
     ('Rómulo Gallegos', 8, CURDATE(), CURDATE()),
     ('Tinaco', 8, CURDATE(), CURDATE()),

     ('Tucupita', 9, CURDATE(), CURDATE()),
     ('Antonio Díaz', 9, CURDATE(), CURDATE()),
     ('Casacoima', 9, CURDATE(), CURDATE()),
     ('Pedernales', 9, CURDATE(), CURDATE()),

     ('Libertador', 10, CURDATE(), CURDATE()),
     ('Sucre', 10, CURDATE(), CURDATE()),
     ('Baruta', 10, CURDATE(), CURDATE()),
     ('Chacao', 10, CURDATE(), CURDATE()),
     ('El Hatillo', 10, CURDATE(), CURDATE()),

     ('Miranda', 11, CURDATE(), CURDATE()),
     ('Acosta', 11, CURDATE(), CURDATE()),
     ('Bolívar', 11, CURDATE(), CURDATE()),
     ('Buchivacoa', 11, CURDATE(), CURDATE()),
     ('Cacique Manaure', 11, CURDATE(), CURDATE()),
     ('Carirubana', 11, CURDATE(), CURDATE()),
     ('Colina', 11, CURDATE(), CURDATE()),
     ('Dabajuro', 11, CURDATE(), CURDATE()),
     ('Democracia', 11, CURDATE(), CURDATE()),
     ('Falcón', 11, CURDATE(), CURDATE()),
     ('Federación', 11, CURDATE(), CURDATE()),
     ('Jacura', 11, CURDATE(), CURDATE()),
     ('Los Taques', 11, CURDATE(), CURDATE()),
     ('Mauroa', 11, CURDATE(), CURDATE()),
     ('Monseñor Iturriza', 11, CURDATE(), CURDATE()),
     ('Palma Sola', 11, CURDATE(), CURDATE()),
     ('Petit', 11, CURDATE(), CURDATE()),
     ('Píritu', 11, CURDATE(), CURDATE()),
     ('San Francisco', 11, CURDATE(), CURDATE()),
     ('Silva', 11, CURDATE(), CURDATE()),
     ('Sucre', 11, CURDATE(), CURDATE()),
     ('Tocópero', 11, CURDATE(), CURDATE()),
     ('Unión', 11, CURDATE(), CURDATE()),
     ('Urumaco', 11, CURDATE(), CURDATE()),
     ('Zamora', 11, CURDATE(), CURDATE()),

     ('Juan Germán Roscio', 12, CURDATE(), CURDATE()),
     ('Camaguán', 12, CURDATE(), CURDATE()),
     ('Chaguaramas', 12, CURDATE(), CURDATE()),
     ('El Socorro', 12, CURDATE(), CURDATE()),
     ('Francisco de Miranda', 12, CURDATE(), CURDATE()),
     ('José Félix Ribas', 12, CURDATE(), CURDATE()),
     ('José Tadeo Monagas', 12, CURDATE(), CURDATE()),
     ('Julián Mellado', 12, CURDATE(), CURDATE()),
     ('Las Mercedes', 12, CURDATE(), CURDATE()),
     ('Leonardo Infante', 12, CURDATE(), CURDATE()),
     ('Ortiz', 12, CURDATE(), CURDATE()),
     ('Pedro Zaraza', 12, CURDATE(), CURDATE()),
     ('San Gerónimo de Guayabal', 12, CURDATE(), CURDATE()),
     ('San José de Guaribe', 12, CURDATE(), CURDATE()),
     ('Santa María de Ipire', 12, CURDATE(), CURDATE()),

     ('Iribarren', 13, CURDATE(), CURDATE()),
     ('Andrés Eloy Blanco', 13, CURDATE(), CURDATE()),
     ('Crespo', 13, CURDATE(), CURDATE()),
     ('Jiménez', 13, CURDATE(), CURDATE()),
     ('Morán', 13, CURDATE(), CURDATE()),
     ('Palavecino', 13, CURDATE(), CURDATE()),
     ('Simón Planas', 13, CURDATE(), CURDATE()),
     ('Torres', 13, CURDATE(), CURDATE()),
     ('Urdaneta', 13, CURDATE(), CURDATE()),

     ('Libertador', 14, CURDATE(), CURDATE()),
     ('Alberto Adriani', 14, CURDATE(), CURDATE()),
     ('Andrés Bello', 14, CURDATE(), CURDATE()),
     ('Antonio Pinto Salinas', 14, CURDATE(), CURDATE()),
     ('Aricagua', 14, CURDATE(), CURDATE()),
     ('Arzobispo Chacón', 14, CURDATE(), CURDATE()),
     ('Campo Elías', 14, CURDATE(), CURDATE()),
     ('Caracciolo Parra Olmedo', 14, CURDATE(), CURDATE()),
     ('Cardenal Quintero', 14, CURDATE(), CURDATE()),
     ('Guaraque', 14, CURDATE(), CURDATE()),
     ('Julio César Salas', 14, CURDATE(), CURDATE()),
     ('Justo Briceño', 14, CURDATE(), CURDATE()),
     ('Miranda', 14, CURDATE(), CURDATE()),
     ('Obispo Ramos de Lora', 14, CURDATE(), CURDATE()),
     ('Padre Noguera', 14, CURDATE(), CURDATE()),
     ('Pueblo Llano', 14, CURDATE(), CURDATE()),
     ('Rangel', 14, CURDATE(), CURDATE()),
     ('Rivas Dávila', 14, CURDATE(), CURDATE()),
     ('Santos Marquina', 14, CURDATE(), CURDATE()),
     ('Sucre', 14, CURDATE(), CURDATE()),
     ('Tovar', 14, CURDATE(), CURDATE()),
     ('Tulio Febres Cordero', 14, CURDATE(), CURDATE()),
     ('Zea', 14, CURDATE(), CURDATE()),

     ('Guaicaipuro', 15, CURDATE(), CURDATE()),
     ('Acevedo', 15, CURDATE(), CURDATE()),
     ('Andrés Bello', 15, CURDATE(), CURDATE()),
     ('Baruta', 15, CURDATE(), CURDATE()),
     ('Brión', 15, CURDATE(), CURDATE()),
     ('Buroz', 15, CURDATE(), CURDATE()),
     ('Carrizal', 15, CURDATE(), CURDATE()),
     ('Chacao', 15, CURDATE(), CURDATE()),
     ('Cristóbal Rojas', 15, CURDATE(), CURDATE()),
     ('El Hatillo', 15, CURDATE(), CURDATE()),
     ('Independencia', 15, CURDATE(), CURDATE()),
     ('Los Salias', 15, CURDATE(), CURDATE()),
     ('Páez', 15, CURDATE(), CURDATE()),
     ('Paz Castillo', 15, CURDATE(), CURDATE()),
     ('Pedro Gual', 15, CURDATE(), CURDATE()),
     ('Plaza', 15, CURDATE(), CURDATE()),
     ('Simón Bolívar', 15, CURDATE(), CURDATE()),
     ('Sucre', 15, CURDATE(), CURDATE()),
     ('Tomás Lander', 15, CURDATE(), CURDATE()),
     ('Urdaneta', 15, CURDATE(), CURDATE()),
     ('Zamora', 15, CURDATE(), CURDATE()),

     ('Maturín', 16, CURDATE(), CURDATE()),
     ('Acosta', 16, CURDATE(), CURDATE()),
     ('Aguasay', 16, CURDATE(), CURDATE()),
     ('Bolívar', 16, CURDATE(), CURDATE()),
     ('Caripe', 16, CURDATE(), CURDATE()),
     ('Cedeño', 16, CURDATE(), CURDATE()),
     ('Ezequiel Zamora', 16, CURDATE(), CURDATE()),
     ('Libertador', 16, CURDATE(), CURDATE()),
     ('Piar', 16, CURDATE(), CURDATE()),
     ('Punceres', 16, CURDATE(), CURDATE()),
     ('Santa Bárbara', 16, CURDATE(), CURDATE()),
     ('Sotillo', 16, CURDATE(), CURDATE()),
     ('Uracoa', 16, CURDATE(), CURDATE()),

     ('Arismendi', 17, CURDATE(), CURDATE()),
     ('Antolín del Campo', 17, CURDATE(), CURDATE()),
     ('Díaz', 17, CURDATE(), CURDATE()),
     ('García', 17, CURDATE(), CURDATE()),
     ('Gómez', 17, CURDATE(), CURDATE()),
     ('Maneiro', 17, CURDATE(), CURDATE()),
     ('Marcano', 17, CURDATE(), CURDATE()),
     ('Mariño', 17, CURDATE(), CURDATE()),
     ('Península de Macanao', 17, CURDATE(), CURDATE()),
     ('Tubores', 17, CURDATE(), CURDATE()),
     ('Villalba', 17, CURDATE(), CURDATE()),

     ('Guanare', 18, CURDATE(), CURDATE()),
     ('Agua Blanca', 18, CURDATE(), CURDATE()),
     ('Araure', 18, CURDATE(), CURDATE()),
     ('Esteller', 18, CURDATE(), CURDATE()),
     ('Guanarito', 18, CURDATE(), CURDATE()),
     ('Monseñor José Vicente de Unda', 18, CURDATE(), CURDATE()),
     ('Ospino', 18, CURDATE(), CURDATE()),
     ('Páez', 18, CURDATE(), CURDATE()),
     ('Papelón', 18, CURDATE(), CURDATE()),
     ('San Genaro de Boconoíto', 18, CURDATE(), CURDATE()),
     ('San Rafael de Onoto', 18, CURDATE(), CURDATE()),
     ('Santa Rosalía', 18, CURDATE(), CURDATE()),
     ('Sucre', 18, CURDATE(), CURDATE()),
     ('Turén', 18, CURDATE(), CURDATE()),

     ('Sucre', 19, CURDATE(), CURDATE()),
     ('Andrés Eloy Blanco', 19, CURDATE(), CURDATE()),
     ('Andrés Mata', 19, CURDATE(), CURDATE()),
     ('Arismendi', 19, CURDATE(), CURDATE()),
     ('Benítez', 19, CURDATE(), CURDATE()),
     ('Bermúdez', 19, CURDATE(), CURDATE()),
     ('Bolívar', 19, CURDATE(), CURDATE()),
     ('Cajigal', 19, CURDATE(), CURDATE()),
     ('Cruz Salmerón Acosta', 19, CURDATE(), CURDATE()),
     ('Libertador', 19, CURDATE(), CURDATE()),
     ('Mariño', 19, CURDATE(), CURDATE()),
     ('Mejía', 19, CURDATE(), CURDATE()),
     ('Montes', 19, CURDATE(), CURDATE()),
     ('Ribero', 19, CURDATE(), CURDATE()),
     ('Valdez', 19, CURDATE(), CURDATE()),

     ('San Cristóbal', 20, CURDATE(), CURDATE()),
     ('Andrés Bello', 20, CURDATE(), CURDATE()),
     ('Antonio Rómulo Costa', 20, CURDATE(), CURDATE()),
     ('Ayacucho', 20, CURDATE(), CURDATE()),
     ('Bolívar', 20, CURDATE(), CURDATE()),
     ('Cárdenas', 20, CURDATE(), CURDATE()),
     ('Córdoba', 20, CURDATE(), CURDATE()),
     ('Fernández Feo', 20, CURDATE(), CURDATE()),
     ('Francisco de Miranda', 20, CURDATE(), CURDATE()),
     ('García de Hevia', 20, CURDATE(), CURDATE()),
     ('Guásimos', 20, CURDATE(), CURDATE()),
     ('Independencia', 20, CURDATE(), CURDATE()),
     ('Jáuregui', 20, CURDATE(), CURDATE()),
     ('José María Vargas', 20, CURDATE(), CURDATE()),
     ('Junín', 20, CURDATE(), CURDATE()),
     ('Libertad', 20, CURDATE(), CURDATE()),
     ('Libertador', 20, CURDATE(), CURDATE()),
     ('Lobatera', 20, CURDATE(), CURDATE()),
     ('Michelena', 20, CURDATE(), CURDATE()),
     ('Panamericano', 20, CURDATE(), CURDATE()),
     ('Pedro María Ureña', 20, CURDATE(), CURDATE()),
     ('Rafael Urdaneta', 20, CURDATE(), CURDATE()),
     ('Samuel Darío Maldonado', 20, CURDATE(), CURDATE()),
     ('San Judas Tadeo', 20, CURDATE(), CURDATE()),
     ('Seboruco', 20, CURDATE(), CURDATE()),
     ('Simón Rodríguez', 20, CURDATE(), CURDATE()),
     ('Sucre', 20, CURDATE(), CURDATE()),
     ('Torbes', 20, CURDATE(), CURDATE()),
     ('Uribante', 20, CURDATE(), CURDATE()),

     ('Trujillo', 21, CURDATE(), CURDATE()),
     ('Andrés Bello', 21, CURDATE(), CURDATE()),
     ('Boconó', 21, CURDATE(), CURDATE()),
     ('Bolívar', 21, CURDATE(), CURDATE()),
     ('Candelaria', 21, CURDATE(), CURDATE()),
     ('Carache', 21, CURDATE(), CURDATE()),
     ('Escuque', 21, CURDATE(), CURDATE()),
     ('José Felipe Márquez Cañizales', 21, CURDATE(), CURDATE()),
     ('Juan Vicente Campo Elías', 21, CURDATE(), CURDATE()),
     ('La Ceiba', 21, CURDATE(), CURDATE()),
     ('Miranda', 21, CURDATE(), CURDATE()),
     ('Monte Carmelo', 21, CURDATE(), CURDATE()),
     ('Motatán', 21, CURDATE(), CURDATE()),
     ('Pampán', 21, CURDATE(), CURDATE()),
     ('Pampanito', 21, CURDATE(), CURDATE()),
     ('Rafael Rangel', 21, CURDATE(), CURDATE()),
     ('San Rafael de Carvajal', 21, CURDATE(), CURDATE()),
     ('Sucre', 21, CURDATE(), CURDATE()),
     ('Urdaneta', 21, CURDATE(), CURDATE()),
     ('Valera', 21, CURDATE(), CURDATE()),

     ('Vargas', 22, CURDATE(), CURDATE()),

     ('San Felipe', 23, CURDATE(), CURDATE()),
     ('Arístides Bastidas', 23, CURDATE(), CURDATE()),
     ('Bolívar', 23, CURDATE(), CURDATE()),
     ('Bruzual', 23, CURDATE(), CURDATE()),
     ('Cocorote', 23, CURDATE(), CURDATE()),
     ('Independencia', 23, CURDATE(), CURDATE()),
     ('José Antonio Páez', 23, CURDATE(), CURDATE()),
     ('La Trinidad', 23, CURDATE(), CURDATE()),
     ('Manuel Monge', 23, CURDATE(), CURDATE()),
     ('Nirgua', 23, CURDATE(), CURDATE()),
     ('Peña', 23, CURDATE(), CURDATE()),
     ('Sucre', 23, CURDATE(), CURDATE()),
     ('Urachiche', 23, CURDATE(), CURDATE()),
     ('Veroes', 23, CURDATE(), CURDATE()),

     ('Maracaibo', 24, CURDATE(), CURDATE()),
     ('Almirante Padilla', 24, CURDATE(), CURDATE()),
     ('Baralt', 24, CURDATE(), CURDATE()),
     ('Cabimas', 24, CURDATE(), CURDATE()),
     ('Catatumbo', 24, CURDATE(), CURDATE()),
     ('Colón', 24, CURDATE(), CURDATE()),
     ('Francisco Javier Pulgar', 24, CURDATE(), CURDATE()),
     ('Guajira', 24, CURDATE(), CURDATE()),
     ('Jesús Enrique Lossada', 24, CURDATE(), CURDATE()),
     ('Jesús María Semprún', 24, CURDATE(), CURDATE()),
     ('La Cañada de Urdaneta', 24, CURDATE(), CURDATE()),
     ('Lagunillas', 24, CURDATE(), CURDATE()),
     ('Machiques de Perijá', 24, CURDATE(), CURDATE()),
     ('Mara', 24, CURDATE(), CURDATE()),
     ('Miranda', 24, CURDATE(), CURDATE()),
     ('Rosario de Perijá', 24, CURDATE(), CURDATE()),
     ('San Francisco', 24, CURDATE(), CURDATE()),
     ('Santa Rita', 24, CURDATE(), CURDATE()),
     ('Simón Bolívar', 24, CURDATE(), CURDATE()),
     ('Sucre', 24, CURDATE(), CURDATE()),
     ('Valmore Rodríguez', 24, CURDATE(), CURDATE());